spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: wallet-route
          uri: lb://WALLET-API
          predicates:
            - Path=/wallet/**
          filters:
            - PrefixPath=/api/v1

        - id: identity-route
          uri: lb://IDENTITY-SERVICE
          predicates:
            Path=/users/**
          filters:
            - PrefixPath=/api/v1
#            - AddResponseHeader=X-powered-by,Maver Gateway Service

      discovery:
        locator:
          enabled: true
  main:
    web-application-type: reactive

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9081/realms/WalletAPI
          jwk-set-uri: http://localhost:9081/auth/realms/WalletAPI/protocol/openid-connect/certs



server:
  port: 8083

